name: API Tests

on: [push, pull_request]

jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # or '18'

      - name: Install Newman + reporters (global)
        run: |
          npm i -g newman newman-reporter-html newman-reporter-json newman-reporter-junitfull
          mkdir -p reports

      - name: Run API Tests (single command)
        run: >
          newman run render1.json
          -r cli,html,json,junitfull
          --reporter-html-export reports/html-report.html
          --reporter-json-export reports/json-report.json
          --reporter-junitfull-export reports/junit-report.xml

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: api-test-reports
          path: reports/
